name: test
on: [push, pull_request, workflow_dispatch]
jobs:
  linux-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get -qy update && sudo apt-get -qy install git make libsdl2-dev libz-dev python3-pip && pip install pillow

      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build
        run: CC=gcc make tests
